
export const SYSTEM_TYPE_NAMES = {
  ANIMAL_TYPES: "animal_types",
  RACE_TYPES: "race_types",
  ANIMAL_COLORS: "animal_colors",
  ANIMAL_VITALS: "animal_vitals",
  GENDER_TYPES: "gender_types",
  INSURANCE_TYPES: "insurance_types",
  FOOD_TYPES: "food_types",
  FOOD_EXTRA_TYPES: "food_extra_types",
  EXAMINATION_TYPES: "examination_types",
  FECES_TYPES: "feces_types",
  URINE_TYPES: "urine_types",
  DOSAGE_FREQUENCIES: "dosage_frequencies",
  MEASURE_UNIT_TYPES: "measure_unit_types",
  PROCEDURE_TYPES: "procedure_types",
  MEDICINES: "medicines",
  MEDICINE_CATEGORIES: "medicine_categories",
  ROUTES_OF_ADMINISTRATION: "routes_of_administration",
  PATIENT_DOCUMENT_TYPES: "patient_document_types",
} as const;

export type SystemTypeName = (typeof SYSTEM_TYPE_NAMES)[keyof typeof SYSTEM_TYPE_NAMES];

export const SYSTEM_TYPE_NAMES_VALUES: readonly [SystemTypeName, ...SystemTypeName[]] = [
  SYSTEM_TYPE_NAMES.ANIMAL_TYPES,
  SYSTEM_TYPE_NAMES.RACE_TYPES,
  SYSTEM_TYPE_NAMES.ANIMAL_COLORS,
  SYSTEM_TYPE_NAMES.ANIMAL_VITALS,
  SYSTEM_TYPE_NAMES.GENDER_TYPES,
  SYSTEM_TYPE_NAMES.INSURANCE_TYPES,
  SYSTEM_TYPE_NAMES.FOOD_TYPES,
  SYSTEM_TYPE_NAMES.FOOD_EXTRA_TYPES,
  SYSTEM_TYPE_NAMES.EXAMINATION_TYPES,
  SYSTEM_TYPE_NAMES.FECES_TYPES,
  SYSTEM_TYPE_NAMES.URINE_TYPES,
  SYSTEM_TYPE_NAMES.DOSAGE_FREQUENCIES,
  SYSTEM_TYPE_NAMES.MEASURE_UNIT_TYPES,
  SYSTEM_TYPE_NAMES.PROCEDURE_TYPES,
  SYSTEM_TYPE_NAMES.MEDICINES,
  SYSTEM_TYPE_NAMES.MEDICINE_CATEGORIES,
  SYSTEM_TYPE_NAMES.ROUTES_OF_ADMINISTRATION,
  SYSTEM_TYPE_NAMES.PATIENT_DOCUMENT_TYPES,
];
