export * from "./auth.dto";
export * from "./app.dto";
export * from "./patient.dto";
export * from "./anesthesia.dto";
export * from "./admin.dto";
export * from "./table.dto";
export * from "./table.dto.types";
export * from "./user.dto";
export * from "./params/index";
