export const CLINICAL_SUMMARY_LIMITS = Object.freeze({
  inputJsonCharacters: 18_000,
  noteCharacters: 800,
  recentVitals: 48,
  recentObservations: 40,
});

export const CLINICAL_SUMMARY_TIME_ZONE = "Asia/Jerusalem";

const CASE_SUMMARY_FIELDS = [
  "createdAt",
  "updatedAt",
  "admission.hospitalizationReason",
  "admission.allergicComments",
  "patientSnapshot.ageYears",
  "patientSnapshot.ageMonths",
  "patientSnapshot.weightKg",
  "flags.isAllergic",
  "flags.isEscapePotential",
  "flags.isNPO",
  "flags.isRiskAnesthesia",
  "flags.isHeartMurmur",
  "flags.isAggressive",
  "flags.isAMB",
  "flags.isConvenia",
  "flags.isCerenia",
  "dates.nextInspectionDate",
  "dates.stitchesRemovalDate",
  "refs.animalTypeId",
  "refs.genderTypeId",
  "refs.raceTypeId",
  "comments",
  "dailyPlan.comments",
  "caseDetailsGrid.date",
  "caseDetailsGrid.time",
  "caseDetailsGrid.dateTime",
  "caseDetailsGrid.temperature",
  "caseDetailsGrid.temperatureIsRequired",
  "caseDetailsGrid.pulse",
  "caseDetailsGrid.pulseIsRequired",
  "caseDetailsGrid.respiration",
  "caseDetailsGrid.respirationIsRequired",
  "caseDetailsGrid.urineComments",
  "caseDetailsGrid.urineIsRequired",
  "caseDetailsGrid.fecesComments",
  "caseDetailsGrid.fecesIsRequired",
  "caseDetailsGrid.pukeComments",
  "caseDetailsGrid.pukeIsRequired",
  "caseDetailsGrid.rowComments",
  "caseDetailsGrid.rowCommentsIsRequired",
  "caseDetailsGrid.foodAndWater",
  "caseDetailsGrid.foodAndWaterIsRequired",
  "caseDetailsGrid.foodGiven",
  "caseDetailsGrid.waterGiven",
  "caseDetailsGrid.isBoxClean",
  "caseDetailsGrid.isBoxCleanIsRequired",
  "caseDetailsGrid.isRelease",
  "caseDetailsGrid.isReleaseIsRequired",
  "caseDetailsGrid.isTravel",
  "caseDetailsGrid.isTravelIsRequired",
  "caseDetailsGrid.isPuke",
  "caseDetailsGrid.weigh",
  "caseDetailsGrid.weighIsRequired",
  "caseDetailsGrid.ownerUpdate",
  "caseDetailsGrid.ownerUpdateIsRequired",
  "caseDetailsGrid.urineTypeId",
  "caseDetailsGrid.fecesTypeId",
  "caseDetailsGrid.medicines.medicineId",
  "caseDetailsGrid.medicines.dosageText",
  "caseDetailsGrid.medicines.doseAmount",
  "caseDetailsGrid.medicines.measureUnitTypeId",
  "caseDetailsGrid.medicines.dosageFrequencyId",
  "caseDetailsGrid.medicines.routeOfAdministrationId",
  "caseDetailsGrid.medicines.isGiven",
  "caseDetailsGrid.medicines.isRequired",
  "caseDetailsGrid.medicines.comment",
  "caseDetailsGrid.fluids.medicineId",
  "caseDetailsGrid.fluids.dosageText",
  "caseDetailsGrid.fluids.doseAmount",
  "caseDetailsGrid.fluids.measureUnitTypeId",
  "caseDetailsGrid.fluids.dosageFrequencyId",
  "caseDetailsGrid.fluids.routeOfAdministrationId",
  "caseDetailsGrid.fluids.isGiven",
  "caseDetailsGrid.fluids.isRequired",
  "caseDetailsGrid.fluids.comment",
  "caseDetailsGrid.procedures.typeId",
  "caseDetailsGrid.procedures.isGiven",
  "caseDetailsGrid.procedures.isRequired",
  "caseDetailsGrid.procedures.comment",
  "caseDetailsGrid.foodExtras.typeId",
  "caseDetailsGrid.foodExtras.isGiven",
  "caseDetailsGrid.foodExtras.isRequired",
  "caseDetailsGrid.foodExtras.comment",
  "caseDetailsGrid.examinations.typeId",
  "caseDetailsGrid.examinations.value",
  "caseDetailsGrid.examinations.isRequired",
  "caseDetailsGrid.examinations.comment",
] as const;

export const CASE_SUMMARY_PROJECTION = CASE_SUMMARY_FIELDS.join(" ");

export const CASE_SUMMARY_POPULATE_PATHS = [
  "refs.animalTypeId",
  "refs.genderTypeId",
  "refs.raceTypeId",
  "caseDetailsGrid.medicines.medicineId",
  "caseDetailsGrid.medicines.measureUnitTypeId",
  "caseDetailsGrid.medicines.dosageFrequencyId",
  "caseDetailsGrid.medicines.routeOfAdministrationId",
  "caseDetailsGrid.fluids.medicineId",
  "caseDetailsGrid.fluids.measureUnitTypeId",
  "caseDetailsGrid.fluids.dosageFrequencyId",
  "caseDetailsGrid.fluids.routeOfAdministrationId",
  "caseDetailsGrid.procedures.typeId",
  "caseDetailsGrid.foodExtras.typeId",
  "caseDetailsGrid.examinations.typeId",
  "caseDetailsGrid.urineTypeId",
  "caseDetailsGrid.fecesTypeId",
] as const;
