export const rolesSeed = [
  { oldId: 1, name: "ADMIN" },
  { oldId: 3, name: "רופא" },
  { oldId: 4, name: "אחות" },
  { oldId: 8, name: "קבלה" },
];

export const usersSeed = [
  {
    username: "lili raviv",
    email: "doc2door@gmail.com",
    firstName: "לילי",
    lastName: "מנשה רביב",
    roleOldId: 3,
    isDeleted: false,
  },
  {
    username: "systemAdmin",
    email: "systemAdmin@gmail.com",
    firstName: "System",
    lastName: "Admin",
    roleOldId: 1,
    isDeleted: false,
  },
  {
    username: "testDoctor",
    email: "testdoctor@gmail.com",
    firstName: "Test",
    lastName: "Doctor",
    roleOldId: 3,
    isDeleted: false,
  },
  {
    username: "יעל כץקובר",
    email: "YAELKATZ1990@GMAIL.COM",
    firstName: "יעל",
    lastName: "כץ-קובר",
    roleOldId: 3,
    isDeleted: false,
  },
  {
    username: "testNurse",
    email: "testNurse@gmail.com",
    firstName: "Test",
    lastName: "Nurse",
    roleOldId: 4,
    isDeleted: false,
  },
  {
    username: "Ido Zeev",
    email: "ido.zeev@mail.huji.ac.il",
    firstName: "Ido",
    lastName: "Zeev",
    roleOldId: 4,
    isDeleted: false,
  },
  {
    username: "noa dadon",
    email: "noad024@gmail.com",
    firstName: "noa",
    lastName: "dadon",
    roleOldId: 4,
    isDeleted: false,
  },
  {
    username: "tom oren",
    email: "tom.oren@mail.huji.ac.il",
    firstName: "tom",
    lastName: "oren",
    roleOldId: 3,
    isDeleted: false,
  },
  {
    username: "tehila",
    email: "tehila.bonbon@gmail.com",
    firstName: "תהילה",
    lastName: "ביטון",
    roleOldId: 4,
    isDeleted: false,
  },
  {
    username: "danny israeli",
    email: "dannyisraeli@yahoo.com",
    firstName: "דני",
    lastName: "ישראלי",
    roleOldId: 3,
    isDeleted: false,
  },
  {
    username: "michal",
    email: "michalshuki@gmail.com",
    firstName: "MICHAL",
    lastName: "WEINBERGER",
    roleOldId: 3,
    isDeleted: false,
  },
  {
    username: "igor milshtein",
    email: "milshtein.dvm@gmail.com",
    firstName: "איגור",
    lastName: "מילשטיין",
    roleOldId: 3,
    isDeleted: false,
  },
  {
    username: "may havivian",
    email: "maykero6@gmail.com",
    firstName: "מאי",
    lastName: "חביביאן",
    roleOldId: 8,
    isDeleted: false,
  },
  {
    username: "hagar poremba",
    email: "hagar005@gmail.com",
    firstName: "הגר",
    lastName: "poremba",
    roleOldId: 4,
    isDeleted: false,
  },
  {
    username: "snirAshwal",
    email: "snirashwal@gmail.com",
    firstName: "שניר",
    lastName: "אשואל",
    roleOldId: 1,
    isDeleted: true,
  },
  {
    username: "סנורקה עמילוב",
    email: "systemAdmin@gmail.com",
    firstName: "סנורקה",
    lastName: "עמילוב",
    roleOldId: 4,
    isDeleted: false,
  },
  {
    username: "דריה צרנייב",
    email: "dariya1devi@gmail.com",
    firstName: "דריה",
    lastName: "צ'רנייב",
    roleOldId: 4,
    isDeleted: false,
  },
];
