import {
  SYSTEM_TYPE_NAMES,
  type GetTableDataDTO,
  type SystemTypeName,
} from "@petec/shared";
import type { ColumnDef } from "../../types";
import type { OrderByObj } from "../../utils/TableGenerator/TableGenerator.types";

export const SystemTypes = {
  MEDICINE: SYSTEM_TYPE_NAMES.MEDICINES,
  ANIMAL_COLOR: SYSTEM_TYPE_NAMES.ANIMAL_COLORS,
  ANIMAL_TYPE: SYSTEM_TYPE_NAMES.ANIMAL_TYPES,
  FECES_TYPE: SYSTEM_TYPE_NAMES.FECES_TYPES,
  URINE_TYPE: SYSTEM_TYPE_NAMES.URINE_TYPES,
  FOOD_TYPE: SYSTEM_TYPE_NAMES.FOOD_TYPES,
  GENDER_TYPE: SYSTEM_TYPE_NAMES.GENDER_TYPES,
  RACE_TYPE: SYSTEM_TYPE_NAMES.RACE_TYPES,
  MEASURE_UNIT_TYPE: SYSTEM_TYPE_NAMES.MEASURE_UNIT_TYPES,
  DOSAGE_FREQUENCY_TYPE: SYSTEM_TYPE_NAMES.DOSAGE_FREQUENCIES,
  INSURANCE_TYPE: SYSTEM_TYPE_NAMES.INSURANCE_TYPES,
  FOOD_EXTRAS_TYPE: SYSTEM_TYPE_NAMES.FOOD_EXTRA_TYPES,
  EXAMINATION_TYPE: SYSTEM_TYPE_NAMES.EXAMINATION_TYPES,
  ROUTE_OF_ADMINISTRATION: SYSTEM_TYPE_NAMES.ROUTES_OF_ADMINISTRATION,
  PROCEDURE_TYPE: SYSTEM_TYPE_NAMES.PROCEDURE_TYPES,
  ANIMAL_VITALS: SYSTEM_TYPE_NAMES.ANIMAL_VITALS,
} as const;

export type SystemTypeValue =
  (typeof SystemTypes)[keyof typeof SystemTypes];

export interface SystemTypeConfig {
  query: GetTableDataDTO["tableName"];
  columnsData: ColumnDef[];
  orderBy?: OrderByObj;
  deleteMessage: string;
  deleteUrl: string;
  systemType: SystemTypeValue;
  typeName: SystemTypeName;
}
