export const PATIENT_ROUTE_PATHS = {
  patientPhoto: "/photo/:patientId",
  newPatient: "/new",
  editPatient: "/edit",
  caseDailyDetails: "/case/caseDailyDetails/:caseId",
  caseDailyDetailsWithMaster: "/case/caseDailyDetails/:masterCaseId/:caseId",
  caseDetails: "/case/details/:caseId",
  caseDetailsWithMaster: "/case/details/:masterCaseId/:caseId",
  caseRelease: "/case/release",
  caseReleaseById: "/case/release/:caseId",
  caseArchive: "/case/archive",
  caseDelete: "/case/delete",
  documentsByCase: "/documents/case/:caseId",
  documentUpload: "/documents/upload",
  documentDelete: "/documents/:documentId",
  caseAnesthesia: "/case/anesthesia/:caseId",
  caseCharts: "/case/charts/:caseId",
  dailyPlan: "/dailyPlan",
  calendar: "/calendar/:year/:month",
  caseSuggestions: "/:patientId/case-suggestions/:category",
} as const;
