import { toObjectId, toOptionalObjectId } from "@utils/objectId.utils";
import type { EditPatientDTO } from "@petec/shared";
import type { ICaseDetailsRow } from "@models/case";

const toNumericDoseAmount = (
    value?: number | string | null,
): number | string | undefined =>
    typeof value === "string" ? Number(value) : value ?? undefined;

export const mapGridDtoToRows = (
    grid: NonNullable<EditPatientDTO["caseDetails"]>,
): Partial<ICaseDetailsRow>[] =>
    grid.flat().map((row) => ({
        date: row.date,
        time: row.time,
        index: row.index,
        temperature: row.temperature,
        temperatureIsRequired: row.temperatureIsRequired,
        temperatureIsEditable: row.temperatureIsEditable,
        pulse: row.pulse,
        pulseIsRequired: row.pulseIsRequired,
        pulseIsEditable: row.pulseIsEditable,
        respiration: row.respiration,
        respirationIsRequired: row.respirationIsRequired,
        respirationIsEditable: row.respirationIsEditable,
        urineTypeId: toOptionalObjectId(row.urineTypeId),
        urineComments: row.urineComments,
        urineIsRequired: row.urineIsRequired,
        urineIsEditable: row.urineIsEditable,
        fecesTypeId: toOptionalObjectId(row.fecesTypeId),
        fecesComments: row.fecesComments,
        fecesIsRequired: row.fecesIsRequired,
        fecesIsEditable: row.fecesIsEditable,
        isBoxClean: row.isBoxClean,
        isBoxCleanIsRequired: row.isBoxCleanIsRequired,
        isBoxCleanIsEditable: row.isBoxCleanIsEditable,
        isRelease: row.isRelease,
        isReleaseIsRequired: row.isReleaseIsRequired,
        isReleaseIsEditable: row.isReleaseIsEditable,
        isTravel: row.isTravel,
        isTravelIsRequired: row.isTravelIsRequired,
        isTravelIsEditable: row.isTravelIsEditable,
        weigh: row.weigh,
        weighIsRequired: row.weighIsRequired,
        weighIsEditable: row.weighIsEditable,
        isPuke: row.isPuke,
        pukeComments: row.pukeComments,
        pukeIsRequired: row.pukeIsRequired,
        pukeIsEditable: row.pukeIsEditable,
        rowComments: row.rowComments,
        rowCommentsIsRequired: row.rowCommentsIsRequired,
        rowCommentsIsEditable: row.rowCommentsIsEditable,
        ownerUpdate: row.ownerUpdate,
        ownerUpdateIsRequired: row.ownerUpdateIsRequired,
        ownerUpdateIsEditable: row.ownerUpdateIsEditable,
        foodGiven: row.foodGiven,
        waterGiven: row.waterGiven,
        foodAndWater: row.foodAndWater,
        foodAndWaterIsRequired: row.foodAndWaterIsRequired,
        foodAndWaterIsEditable: row.foodAndWaterIsEditable,
        fluids: row.fluids.map((fluid) => ({
            medicineId: toObjectId(fluid.medicineId),
            dosageText: fluid.dosageText,
            doseAmount: toNumericDoseAmount(fluid.doseAmount),
            measureUnitTypeId: toOptionalObjectId(fluid.measureUnitTypeId),
            dosageFrequencyId: toOptionalObjectId(fluid.dosageFrequencyId),
            routeOfAdministrationId: toOptionalObjectId(
                fluid.routeOfAdministrationId,
            ),
            isGiven: fluid.isGiven,
            isRequired: fluid.isRequired,
            isEditable: fluid.isEditable,
            comment: fluid.comment,
        })),
        medicines: row.medicines.map((medicine) => ({
            medicineId: toObjectId(medicine.medicineId),
            dosageText: medicine.dosageText,
            doseAmount: toNumericDoseAmount(medicine.doseAmount),
            measureUnitTypeId: toOptionalObjectId(medicine.measureUnitTypeId),
            dosageFrequencyId: toOptionalObjectId(medicine.dosageFrequencyId),
            routeOfAdministrationId: toOptionalObjectId(
                medicine.routeOfAdministrationId,
            ),
            isGiven: medicine.isGiven,
            isRequired: medicine.isRequired,
            isEditable: medicine.isEditable,
            comment: medicine.comment,
        })),
        procedures: row.procedures.map((procedure) => ({
            typeId: toObjectId(procedure.typeId),
            isGiven: procedure.isGiven,
            isRequired: procedure.isRequired,
            isEditable: procedure.isEditable,
            comment: procedure.comment,
        })),
        examinations: row.examinations.map((examination) => ({
            typeId: toObjectId(examination.typeId),
            value: examination.value ?? null,
            isRequired: examination.isRequired,
            isEditable: examination.isEditable,
            comment: examination.comment,
        })),
        foodExtras: row.foodExtras.map((foodExtra) => ({
            typeId: toObjectId(foodExtra.typeId),
            isGiven: foodExtra.isGiven,
            isRequired: foodExtra.isRequired,
            isEditable: foodExtra.isEditable,
            comment: foodExtra.comment,
        })),
    }));
