import { UPLOAD } from "@petec/shared";

export const PATIENT_STORAGE = {
  DOCUMENTS_PREFIX: UPLOAD.PATIENT_DOCUMENTS_PREFIX,
  PHOTOS_PREFIX: UPLOAD.PATIENT_PHOTOS_PREFIX,
  DEFAULT_DOCUMENT_FILE_NAME: "document",
} as const;
