import { UPLOAD } from "@petec/shared";

export const PATIENT_STORAGE = {
  DOCUMENTS_PREFIX: UPLOAD.PATIENT_DOCUMENTS_PREFIX,
  DOCUMENTS_FOLDER: UPLOAD.PATIENT_DOCUMENTS_DIR,
  PHOTOS_PREFIX: UPLOAD.PATIENT_PHOTOS_PREFIX,
  PHOTOS_FOLDER: UPLOAD.PATIENT_PHOTOS_DIR,
  DEFAULT_PHOTO_FILE_NAME: "patient-photo",
  DEFAULT_DOCUMENT_FILE_NAME: "document",
} as const;
